stages:
  load_data:
    cmd: python refactoring/load_data.py ${data.filepath} ${data.processed}train_test_data.csv
    deps:
      - refactoring/load_data.py
      - ${data.filepath}
    outs:
      - ${data.processed}train_test_data.csv

  preprocess:
    cmd: python refactoring/preprocess_data.py ${data.processed}train_test_data.csv ${data.processed}X_train.csv ${data.processed}X_test.csv ${data.processed}y_train.csv ${data.processed}y_test.csv
    deps:
      - refactoring/preprocess_data.py
      - ${data.processed}train_test_data.csv
    outs:
      - ${data.processed}X_train.csv
      - ${data.processed}X_test.csv
      - ${data.processed}y_train.csv
      - ${data.processed}y_test.csv

  train:
    cmd: python refactoring/train.py ${data.processed}X_train.csv ${data.processed}y_train.csv ${data.models}model.pkl
    deps:
      - refactoring/train.py
      - ${data.processed}X_train.csv
      - ${data.processed}y_train.csv
    outs:
      - ${data.models}model.pkl

  evaluate:
    cmd: python refactoring/evaluate.py ${data.models}model.pkl ${data.processed}X_test.csv ${data.processed}y_test.csv
    deps:
      - refactoring/evaluate.py
      - ${data.models}model.pkl
      - ${data.processed}X_test.csv
      - ${data.processed}y_test.csv
