stages:
  load_data:
    cmd: python refactoring/load_data_v2.py ${data.filepath} ${data.processed}train_test_data.csv
    deps:
      - refactoring/load_data_v2.py
      - ${data.filepath}
    outs:
      - ${data.processed}train_test_data.csv

  preprocess:
    cmd: python refactoring/preprocess_data_v2.py ${data.processed}train_test_data.csv ${data.processed}X_train.csv ${data.processed}X_test.csv ${data.processed}y_train.csv ${data.processed}y_test.csv
    deps:
      - refactoring/preprocess_data_v2.py
      - ${data.processed}train_test_data.csv
    outs:
      - ${data.processed}X_train.csv
      - ${data.processed}X_test.csv
      - ${data.processed}y_train.csv
      - ${data.processed}y_test.csv

  train_logistic:
    cmd: python refactoring/train_v2.py data/processed/X_train.csv data/processed/y_train.csv logistic_regression
    deps:
      - refactoring/train_v2.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/logistic_regression_model.pkl

  train_random_forest:
    cmd: python refactoring/train_v2.py data/processed/X_train.csv data/processed/y_train.csv random_forest
    deps:
      - refactoring/train_v2.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/random_forest_model.pkl

  evaluate_logistic:
    cmd: python refactoring/evaluate_v2.py models/logistic_regression_model.pkl data/processed/X_test.csv data/processed/y_test.csv reports/logistic_evaluation.txt
    deps:
      - refactoring/evaluate_v2.py
      - models/logistic_regression_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - reports/logistic_evaluation.txt


  evaluate_random_forest:
    cmd: python refactoring/evaluate_v2.py models/random_forest_model.pkl data/processed/X_test.csv data/processed/y_test.csv reports/random_forest_evaluation.txt
    deps:
      - refactoring/evaluate_v2.py
      - models/random_forest_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - reports/random_forest_evaluation.txt
